grpc:
  greeting:
    hostname: localhost
    port: 6565

spring:
  threads:
    virtual:
      enabled: true
  graphql:
    graphiql:
      enabled: true
      path: /gui

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 18081
